// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIYjDFWmPy6xTZ7wPkxcddQCQRXEoJ3uQ',
    appId: '1:113187552287:web:030b411b0effdb0b5a292a',
    messagingSenderId: '113187552287',
    projectId: 'cima-optimizer',
    authDomain: 'cima-optimizer.firebaseapp.com',
    storageBucket: 'cima-optimizer.firebasestorage.app',
    measurementId: 'G-Y8XQ1ZT0H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmibjZufQuEp1g4piGAcucmQ7wA88xq7o',
    appId: '1:113187552287:android:279e3b84e2c5c0115a292a',
    messagingSenderId: '113187552287',
    projectId: 'cima-optimizer',
    storageBucket: 'cima-optimizer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmhEAkYDtrvBFB9VE_UMnE--lmvrdk0Ck',
    appId: '1:113187552287:ios:7f896852e811df725a292a',
    messagingSenderId: '113187552287',
    projectId: 'cima-optimizer',
    storageBucket: 'cima-optimizer.firebasestorage.app',
    iosBundleId: 'com.example.cimaOptimizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmhEAkYDtrvBFB9VE_UMnE--lmvrdk0Ck',
    appId: '1:113187552287:ios:7f896852e811df725a292a',
    messagingSenderId: '113187552287',
    projectId: 'cima-optimizer',
    storageBucket: 'cima-optimizer.firebasestorage.app',
    iosBundleId: 'com.example.cimaOptimizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIYjDFWmPy6xTZ7wPkxcddQCQRXEoJ3uQ',
    appId: '1:113187552287:web:f7f81ec3f73bccba5a292a',
    messagingSenderId: '113187552287',
    projectId: 'cima-optimizer',
    authDomain: 'cima-optimizer.firebaseapp.com',
    storageBucket: 'cima-optimizer.firebasestorage.app',
    measurementId: 'G-R18QPS73CP',
  );

}